#############################################################################
# Makefile for building: MoteSense
# Generated by qmake (2.01a) (Qt 4.6.2) on: Sat Apr 3 09:37:37 2010
# Project:  MoteSense.pro
# Template: app
# Command: /home/jlafon/qtsdk-2010.02/qt/bin/qmake -spec /home/jlafon/qtsdk-2010.02/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile MoteSense.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/home/jlafon/qtsdk-2010.02/qt/mkspecs/linux-g++-64 -I. -I/home/jlafon/qtsdk-2010.02/qt/include/QtCore -I/home/jlafon/qtsdk-2010.02/qt/include/QtNetwork -I/home/jlafon/qtsdk-2010.02/qt/include/QtGui -I/home/jlafon/qtsdk-2010.02/qt/include/QtSql -I/home/jlafon/qtsdk-2010.02/qt/include -I/usr/local/qwt-5.2.0/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/jlafon/qtsdk-2010.02/qt/lib
LIBS          = $(SUBLIBS)  -L/home/jlafon/qtsdk-2010.02/qt/lib /usr/local/qwt-5.2.0/lib/libqwt.so.5.2.0 -lQtSql -L/home/jlafon/qtsdk-2010.02/qt/lib -lQtGui -L/usr/X11R6/lib64 -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/jlafon/qtsdk-2010.02/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		packethandler.cpp \
		motereading.cpp \
		data_plot.cpp \
		graphwindow.cpp moc_mainwindow.cpp \
		moc_packethandler.cpp \
		moc_data_plot.cpp
OBJECTS       = main.o \
		mainwindow.o \
		packethandler.o \
		motereading.o \
		data_plot.o \
		graphwindow.o \
		moc_mainwindow.o \
		moc_packethandler.o \
		moc_data_plot.o
DIST          = /home/jlafon/qtsdk-2010.02/qt/mkspecs/common/g++.conf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/common/unix.conf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/common/linux.conf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/qconfig.pri \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/qt_config.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/default_pre.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/debug.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/default_post.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/warn_on.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/qt.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/moc.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/resources.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/uic.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/yacc.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/lex.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf \
		MoteSense.pro
QMAKE_TARGET  = MoteSense
DESTDIR       = 
TARGET        = MoteSense

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MoteSense.pro  /home/jlafon/qtsdk-2010.02/qt/mkspecs/linux-g++-64/qmake.conf /home/jlafon/qtsdk-2010.02/qt/mkspecs/common/g++.conf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/common/unix.conf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/common/linux.conf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/qconfig.pri \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/qt_config.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/default_pre.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/debug.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/default_post.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/warn_on.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/qt.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/moc.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/resources.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/uic.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/yacc.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/lex.prf \
		/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf \
		/home/jlafon/qtsdk-2010.02/qt/lib/libQtSql.prl \
		/home/jlafon/qtsdk-2010.02/qt/lib/libQtCore.prl \
		/home/jlafon/qtsdk-2010.02/qt/lib/libQtGui.prl \
		/home/jlafon/qtsdk-2010.02/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec /home/jlafon/qtsdk-2010.02/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile MoteSense.pro
/home/jlafon/qtsdk-2010.02/qt/mkspecs/common/g++.conf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/common/unix.conf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/common/linux.conf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/qconfig.pri:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/qt_config.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/default_pre.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/debug.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/default_post.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/warn_on.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/qt.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/moc.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/resources.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/uic.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/yacc.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/lex.prf:
/home/jlafon/qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf:
/home/jlafon/qtsdk-2010.02/qt/lib/libQtSql.prl:
/home/jlafon/qtsdk-2010.02/qt/lib/libQtCore.prl:
/home/jlafon/qtsdk-2010.02/qt/lib/libQtGui.prl:
/home/jlafon/qtsdk-2010.02/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /home/jlafon/qtsdk-2010.02/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile MoteSense.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MoteSense1.0.0 || $(MKDIR) .tmp/MoteSense1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MoteSense1.0.0/ && $(COPY_FILE) --parents mainwindow.h packethandler.h motereading.h data_plot.h graphwindow.h .tmp/MoteSense1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp packethandler.cpp motereading.cpp data_plot.cpp graphwindow.cpp .tmp/MoteSense1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/MoteSense1.0.0/ && (cd `dirname .tmp/MoteSense1.0.0` && $(TAR) MoteSense1.0.0.tar MoteSense1.0.0 && $(COMPRESS) MoteSense1.0.0.tar) && $(MOVE) `dirname .tmp/MoteSense1.0.0`/MoteSense1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MoteSense1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_packethandler.cpp moc_data_plot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_packethandler.cpp moc_data_plot.cpp
moc_mainwindow.cpp: packethandler.h \
		motereading.h \
		mainwindow.h
	/home/jlafon/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_packethandler.cpp: motereading.h \
		packethandler.h
	/home/jlafon/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) packethandler.h -o moc_packethandler.cpp

moc_data_plot.cpp: packethandler.h \
		motereading.h \
		data_plot.h
	/home/jlafon/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) data_plot.h -o moc_data_plot.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/jlafon/qtsdk-2010.02/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		packethandler.h \
		motereading.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		packethandler.h \
		motereading.h \
		ui_mainwindow.h \
		data_plot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

packethandler.o: packethandler.cpp packethandler.h \
		motereading.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o packethandler.o packethandler.cpp

motereading.o: motereading.cpp motereading.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o motereading.o motereading.cpp

data_plot.o: data_plot.cpp data_plot.h \
		packethandler.h \
		motereading.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data_plot.o data_plot.cpp

graphwindow.o: graphwindow.cpp graphwindow.h \
		mainwindow.h \
		packethandler.h \
		motereading.h \
		ui_mainwindow.h \
		data_plot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphwindow.o graphwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_packethandler.o: moc_packethandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_packethandler.o moc_packethandler.cpp

moc_data_plot.o: moc_data_plot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_data_plot.o moc_data_plot.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

